
package com.sstl.webservices.SatisfactionOperate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SatisfactionOperateSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SatisfactionOperateSoap {


    /**
     * 
     * @param password
     * @param lmTeSatisfaction
     * @param account
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Submit", action = "http://tempuri.org/Submit")
    @WebResult(name = "SubmitResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Submit", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.SatisfactionOperate.Submit")
    @ResponseWrapper(localName = "SubmitResponse", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.SatisfactionOperate.SubmitResponse")
    public String submit(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "LmTeSatisfaction", targetNamespace = "http://tempuri.org/")
        LmTeSatisfaction lmTeSatisfaction);

}
