
package com.sstl.webservices.ProjectOperateforWeChat;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProjectOperateforWeChatSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProjectOperateforWeChatSoap {


    /**
     * 
     * @param encryptCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CheckProjectByEncryptCode", action = "http://tempuri.org/CheckProjectByEncryptCode")
    @WebResult(name = "CheckProjectByEncryptCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CheckProjectByEncryptCode", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.ProjectOperateforWeChat.CheckProjectByEncryptCode")
    @ResponseWrapper(localName = "CheckProjectByEncryptCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.ProjectOperateforWeChat.CheckProjectByEncryptCodeResponse")
    public String checkProjectByEncryptCode(
        @WebParam(name = "EncryptCode", targetNamespace = "http://tempuri.org/")
        String encryptCode);

    /**
     * 
     * @param password
     * @param userId
     * @param account
     * @return
     *     returns int
     */
    @WebMethod(operationName = "GetMyProjectCount", action = "http://tempuri.org/GetMyProjectCount")
    @WebResult(name = "GetMyProjectCountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMyProjectCount", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.ProjectOperateforWeChat.GetMyProjectCount")
    @ResponseWrapper(localName = "GetMyProjectCountResponse", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.ProjectOperateforWeChat.GetMyProjectCountResponse")
    public int getMyProjectCount(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "UserId", targetNamespace = "http://tempuri.org/")
        int userId);

    /**
     * 
     * @param password
     * @param userId
     * @param account
     * @return
     *     returns com.sstl.webservices.ProjectOperateforWeChat.ArrayOfLmTeProject
     */
    @WebMethod(operationName = "GetMyProjectList", action = "http://tempuri.org/GetMyProjectList")
    @WebResult(name = "GetMyProjectListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMyProjectList", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.ProjectOperateforWeChat.GetMyProjectList")
    @ResponseWrapper(localName = "GetMyProjectListResponse", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.ProjectOperateforWeChat.GetMyProjectListResponse")
    public ArrayOfLmTeProject getMyProjectList(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "UserId", targetNamespace = "http://tempuri.org/")
        int userId);

    /**
     * 
     * @param password
     * @param pageIndex
     * @param pageSize
     * @param userId
     * @param account
     * @return
     *     returns com.sstl.webservices.ProjectOperateforWeChat.ArrayOfLmTeProject
     */
    @WebMethod(operationName = "GetMyProjectListbyPage", action = "http://tempuri.org/GetMyProjectListbyPage")
    @WebResult(name = "GetMyProjectListbyPageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMyProjectListbyPage", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.ProjectOperateforWeChat.GetMyProjectListbyPage")
    @ResponseWrapper(localName = "GetMyProjectListbyPageResponse", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.ProjectOperateforWeChat.GetMyProjectListbyPageResponse")
    public ArrayOfLmTeProject getMyProjectListbyPage(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "UserId", targetNamespace = "http://tempuri.org/")
        int userId,
        @WebParam(name = "PageSize", targetNamespace = "http://tempuri.org/")
        int pageSize,
        @WebParam(name = "PageIndex", targetNamespace = "http://tempuri.org/")
        int pageIndex);

    /**
     * 
     * @param password
     * @param projectId
     * @param account
     * @return
     *     returns com.sstl.webservices.ProjectOperateforWeChat.LmTeProject
     */
    @WebMethod(operationName = "GetProject", action = "http://tempuri.org/GetProject")
    @WebResult(name = "GetProjectResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetProject", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.ProjectOperateforWeChat.GetProject")
    @ResponseWrapper(localName = "GetProjectResponse", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.ProjectOperateforWeChat.GetProjectResponse")
    public LmTeProject getProject(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "ProjectId", targetNamespace = "http://tempuri.org/")
        int projectId);

    /**
     * 
     * @param password
     * @param projectId
     * @param account
     * @return
     *     returns com.sstl.webservices.ProjectOperateforWeChat.ArrayOfLmTeProjectuser
     */
    @WebMethod(operationName = "GetProjectuserList", action = "http://tempuri.org/GetProjectuserList")
    @WebResult(name = "GetProjectuserListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetProjectuserList", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.ProjectOperateforWeChat.GetProjectuserList")
    @ResponseWrapper(localName = "GetProjectuserListResponse", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.ProjectOperateforWeChat.GetProjectuserListResponse")
    public ArrayOfLmTeProjectuser getProjectuserList(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "ProjectId", targetNamespace = "http://tempuri.org/")
        int projectId);

    /**
     * 
     * @param password
     * @param projectId
     * @param account
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetFlowUrl", action = "http://tempuri.org/GetFlowUrl")
    @WebResult(name = "GetFlowUrlResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetFlowUrl", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.ProjectOperateforWeChat.GetFlowUrl")
    @ResponseWrapper(localName = "GetFlowUrlResponse", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.ProjectOperateforWeChat.GetFlowUrlResponse")
    public String getFlowUrl(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "ProjectId", targetNamespace = "http://tempuri.org/")
        int projectId);

    /**
     * 
     * @param password
     * @param projectId
     * @param account
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetExpertFinishDt", action = "http://tempuri.org/GetExpertFinishDt")
    @WebResult(name = "GetExpertFinishDtResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetExpertFinishDt", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.ProjectOperateforWeChat.GetExpertFinishDt")
    @ResponseWrapper(localName = "GetExpertFinishDtResponse", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.ProjectOperateforWeChat.GetExpertFinishDtResponse")
    public String getExpertFinishDt(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "ProjectId", targetNamespace = "http://tempuri.org/")
        int projectId);

    /**
     * 
     * @param password
     * @param lmTeProject
     * @param userId
     * @param account
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SaveProject", action = "http://tempuri.org/SaveProject")
    @WebResult(name = "SaveProjectResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SaveProject", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.ProjectOperateforWeChat.SaveProject")
    @ResponseWrapper(localName = "SaveProjectResponse", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.ProjectOperateforWeChat.SaveProjectResponse")
    public String saveProject(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "LmTeProject", targetNamespace = "http://tempuri.org/")
        LmTeProject lmTeProject,
        @WebParam(name = "UserId", targetNamespace = "http://tempuri.org/")
        int userId);

    /**
     * 
     * @param password
     * @param lmTeProject
     * @param userId
     * @param account
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ProjectCheckPass", action = "http://tempuri.org/ProjectCheckPass")
    @WebResult(name = "ProjectCheckPassResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProjectCheckPass", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.ProjectOperateforWeChat.ProjectCheckPass")
    @ResponseWrapper(localName = "ProjectCheckPassResponse", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.ProjectOperateforWeChat.ProjectCheckPassResponse")
    public String projectCheckPass(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "LmTeProject", targetNamespace = "http://tempuri.org/")
        LmTeProject lmTeProject,
        @WebParam(name = "UserId", targetNamespace = "http://tempuri.org/")
        int userId);

    /**
     * 
     * @param password
     * @param lmTeProject
     * @param userId
     * @param account
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ProjectCheckNoPass", action = "http://tempuri.org/ProjectCheckNoPass")
    @WebResult(name = "ProjectCheckNoPassResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProjectCheckNoPass", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.ProjectOperateforWeChat.ProjectCheckNoPass")
    @ResponseWrapper(localName = "ProjectCheckNoPassResponse", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.ProjectOperateforWeChat.ProjectCheckNoPassResponse")
    public String projectCheckNoPass(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "LmTeProject", targetNamespace = "http://tempuri.org/")
        LmTeProject lmTeProject,
        @WebParam(name = "UserId", targetNamespace = "http://tempuri.org/")
        int userId);

}
