
package com.sstl.webservices.ProjectOperateforWeChat;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProjectOperateforWeChat", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://192.168.250.54:7070/WebServices/wechat/ProjectOperateforWeChat.asmx?wsdl")
public class ProjectOperateforWeChat
    extends Service
{

    private final static URL PROJECTOPERATEFORWECHAT_WSDL_LOCATION;
    private final static WebServiceException PROJECTOPERATEFORWECHAT_EXCEPTION;
    private final static QName PROJECTOPERATEFORWECHAT_QNAME = new QName("http://tempuri.org/", "ProjectOperateforWeChat");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.250.54:7070/WebServices/wechat/ProjectOperateforWeChat.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROJECTOPERATEFORWECHAT_WSDL_LOCATION = url;
        PROJECTOPERATEFORWECHAT_EXCEPTION = e;
    }

    public ProjectOperateforWeChat() {
        super(__getWsdlLocation(), PROJECTOPERATEFORWECHAT_QNAME);
    }

    public ProjectOperateforWeChat(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROJECTOPERATEFORWECHAT_QNAME, features);
    }

    public ProjectOperateforWeChat(URL wsdlLocation) {
        super(wsdlLocation, PROJECTOPERATEFORWECHAT_QNAME);
    }

    public ProjectOperateforWeChat(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROJECTOPERATEFORWECHAT_QNAME, features);
    }

    public ProjectOperateforWeChat(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProjectOperateforWeChat(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProjectOperateforWeChatSoap
     */
    @WebEndpoint(name = "ProjectOperateforWeChatSoap")
    public ProjectOperateforWeChatSoap getProjectOperateforWeChatSoap() {
        return super.getPort(new QName("http://tempuri.org/", "ProjectOperateforWeChatSoap"), ProjectOperateforWeChatSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProjectOperateforWeChatSoap
     */
    @WebEndpoint(name = "ProjectOperateforWeChatSoap")
    public ProjectOperateforWeChatSoap getProjectOperateforWeChatSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ProjectOperateforWeChatSoap"), ProjectOperateforWeChatSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns ProjectOperateforWeChatSoap
     */
    @WebEndpoint(name = "ProjectOperateforWeChatSoap12")
    public ProjectOperateforWeChatSoap getProjectOperateforWeChatSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "ProjectOperateforWeChatSoap12"), ProjectOperateforWeChatSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProjectOperateforWeChatSoap
     */
    @WebEndpoint(name = "ProjectOperateforWeChatSoap12")
    public ProjectOperateforWeChatSoap getProjectOperateforWeChatSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ProjectOperateforWeChatSoap12"), ProjectOperateforWeChatSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROJECTOPERATEFORWECHAT_EXCEPTION!= null) {
            throw PROJECTOPERATEFORWECHAT_EXCEPTION;
        }
        return PROJECTOPERATEFORWECHAT_WSDL_LOCATION;
    }

}
