
package com.sstl.webservices.SendMessage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SendMessageSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SendMessageSoap {


    /**
     * 
     * @param password
     * @param mobile
     * @param context
     * @param userName
     * @param suffix
     */
    @WebMethod(operationName = "Send", action = "http://tempuri.org/Send")
    @RequestWrapper(localName = "Send", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.SendMessage.Send")
    @ResponseWrapper(localName = "SendResponse", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.SendMessage.SendResponse")
    public void send(
        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/")
        ArrayOfString mobile,
        @WebParam(name = "Context", targetNamespace = "http://tempuri.org/")
        String context,
        @WebParam(name = "Suffix", targetNamespace = "http://tempuri.org/")
        String suffix);

}
