
package com.sstl.webservices.ProjectService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProjectServices", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://192.168.250.54:8088/webservices/projectservices.asmx?wsdl")
public class ProjectServices
    extends Service
{

    private final static URL PROJECTSERVICES_WSDL_LOCATION;
    private final static WebServiceException PROJECTSERVICES_EXCEPTION;
    private final static QName PROJECTSERVICES_QNAME = new QName("http://tempuri.org/", "ProjectServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.250.54:8088/webservices/projectservices.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROJECTSERVICES_WSDL_LOCATION = url;
        PROJECTSERVICES_EXCEPTION = e;
    }

    public ProjectServices() {
        super(__getWsdlLocation(), PROJECTSERVICES_QNAME);
    }

    public ProjectServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROJECTSERVICES_QNAME, features);
    }

    public ProjectServices(URL wsdlLocation) {
        super(wsdlLocation, PROJECTSERVICES_QNAME);
    }

    public ProjectServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROJECTSERVICES_QNAME, features);
    }

    public ProjectServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProjectServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProjectServicesSoap
     */
    @WebEndpoint(name = "ProjectServicesSoap")
    public ProjectServicesSoap getProjectServicesSoap() {
        return super.getPort(new QName("http://tempuri.org/", "ProjectServicesSoap"), ProjectServicesSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProjectServicesSoap
     */
    @WebEndpoint(name = "ProjectServicesSoap")
    public ProjectServicesSoap getProjectServicesSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ProjectServicesSoap"), ProjectServicesSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns ProjectServicesSoap
     */
    @WebEndpoint(name = "ProjectServicesSoap12")
    public ProjectServicesSoap getProjectServicesSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "ProjectServicesSoap12"), ProjectServicesSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProjectServicesSoap
     */
    @WebEndpoint(name = "ProjectServicesSoap12")
    public ProjectServicesSoap getProjectServicesSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ProjectServicesSoap12"), ProjectServicesSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROJECTSERVICES_EXCEPTION!= null) {
            throw PROJECTSERVICES_EXCEPTION;
        }
        return PROJECTSERVICES_WSDL_LOCATION;
    }

}
