
package com.sstl.webservices.ProjectService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProjectServicesSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProjectServicesSoap {


    /**
     * 
     * @param password
     * @param projectCode
     * @param describe
     * @param projectId
     * @param account
     * @param projectstatus
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "ProjectStatusChange", action = "http://tempuri.org/ProjectStatusChange")
    @WebResult(name = "ProjectStatusChangeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProjectStatusChange", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.ProjectService.ProjectStatusChange")
    @ResponseWrapper(localName = "ProjectStatusChangeResponse", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.ProjectService.ProjectStatusChangeResponse")
    public boolean projectStatusChange(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "ProjectId", targetNamespace = "http://tempuri.org/")
        int projectId,
        @WebParam(name = "ProjectCode", targetNamespace = "http://tempuri.org/")
        String projectCode,
        @WebParam(name = "projectstatus", targetNamespace = "http://tempuri.org/")
        PrjStatus projectstatus,
        @WebParam(name = "Describe", targetNamespace = "http://tempuri.org/")
        String describe);

    /**
     * 
     * @param password
     * @param mobile
     * @param account
     * @return
     *     returns com.sstl.webservices.ProjectService.ArrayOfProject
     */
    @WebMethod(operationName = "GetProjectList", action = "http://tempuri.org/GetProjectList")
    @WebResult(name = "GetProjectListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetProjectList", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.ProjectService.GetProjectList")
    @ResponseWrapper(localName = "GetProjectListResponse", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.ProjectService.GetProjectListResponse")
    public ArrayOfProject getProjectList(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/")
        String mobile);

    /**
     * 
     * @return
     *     returns com.sstl.webservices.ProjectService.ArrayOfDictionaryEntry
     */
    @WebMethod(operationName = "GetStatusList", action = "http://tempuri.org/GetStatusList")
    @WebResult(name = "GetStatusListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStatusList", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.ProjectService.GetStatusList")
    @ResponseWrapper(localName = "GetStatusListResponse", targetNamespace = "http://tempuri.org/", className = "com.sstl.webservices.ProjectService.GetStatusListResponse")
    public ArrayOfDictionaryEntry getStatusList();

}
