
package com.sstl.webservices.SendMessage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SendMessage", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://192.168.250.54:5901/SendMessage.asmx?wsdl")
public class SendMessage
    extends Service
{

    private final static URL SENDMESSAGE_WSDL_LOCATION;
    private final static WebServiceException SENDMESSAGE_EXCEPTION;
    private final static QName SENDMESSAGE_QNAME = new QName("http://tempuri.org/", "SendMessage");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.250.54:5901/SendMessage.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SENDMESSAGE_WSDL_LOCATION = url;
        SENDMESSAGE_EXCEPTION = e;
    }

    public SendMessage() {
        super(__getWsdlLocation(), SENDMESSAGE_QNAME);
    }

    public SendMessage(WebServiceFeature... features) {
        super(__getWsdlLocation(), SENDMESSAGE_QNAME, features);
    }

    public SendMessage(URL wsdlLocation) {
        super(wsdlLocation, SENDMESSAGE_QNAME);
    }

    public SendMessage(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SENDMESSAGE_QNAME, features);
    }

    public SendMessage(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SendMessage(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SendMessageSoap
     */
    @WebEndpoint(name = "SendMessageSoap")
    public SendMessageSoap getSendMessageSoap() {
        return super.getPort(new QName("http://tempuri.org/", "SendMessageSoap"), SendMessageSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendMessageSoap
     */
    @WebEndpoint(name = "SendMessageSoap")
    public SendMessageSoap getSendMessageSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "SendMessageSoap"), SendMessageSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns SendMessageSoap
     */
    @WebEndpoint(name = "SendMessageSoap12")
    public SendMessageSoap getSendMessageSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "SendMessageSoap12"), SendMessageSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendMessageSoap
     */
    @WebEndpoint(name = "SendMessageSoap12")
    public SendMessageSoap getSendMessageSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "SendMessageSoap12"), SendMessageSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SENDMESSAGE_EXCEPTION!= null) {
            throw SENDMESSAGE_EXCEPTION;
        }
        return SENDMESSAGE_WSDL_LOCATION;
    }

}
