
package com.sstl.webservices.SatisfactionOperate;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SatisfactionOperate", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://192.168.250.54:7070/WebServices/WeChat/SatisfactionOperate.asmx?wsdl")
public class SatisfactionOperate
    extends Service
{

    private final static URL SATISFACTIONOPERATE_WSDL_LOCATION;
    private final static WebServiceException SATISFACTIONOPERATE_EXCEPTION;
    private final static QName SATISFACTIONOPERATE_QNAME = new QName("http://tempuri.org/", "SatisfactionOperate");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.250.54:7070/WebServices/WeChat/SatisfactionOperate.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SATISFACTIONOPERATE_WSDL_LOCATION = url;
        SATISFACTIONOPERATE_EXCEPTION = e;
    }

    public SatisfactionOperate() {
        super(__getWsdlLocation(), SATISFACTIONOPERATE_QNAME);
    }

    public SatisfactionOperate(WebServiceFeature... features) {
        super(__getWsdlLocation(), SATISFACTIONOPERATE_QNAME, features);
    }

    public SatisfactionOperate(URL wsdlLocation) {
        super(wsdlLocation, SATISFACTIONOPERATE_QNAME);
    }

    public SatisfactionOperate(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SATISFACTIONOPERATE_QNAME, features);
    }

    public SatisfactionOperate(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SatisfactionOperate(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SatisfactionOperateSoap
     */
    @WebEndpoint(name = "SatisfactionOperateSoap")
    public SatisfactionOperateSoap getSatisfactionOperateSoap() {
        return super.getPort(new QName("http://tempuri.org/", "SatisfactionOperateSoap"), SatisfactionOperateSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SatisfactionOperateSoap
     */
    @WebEndpoint(name = "SatisfactionOperateSoap")
    public SatisfactionOperateSoap getSatisfactionOperateSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "SatisfactionOperateSoap"), SatisfactionOperateSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns SatisfactionOperateSoap
     */
    @WebEndpoint(name = "SatisfactionOperateSoap12")
    public SatisfactionOperateSoap getSatisfactionOperateSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "SatisfactionOperateSoap12"), SatisfactionOperateSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SatisfactionOperateSoap
     */
    @WebEndpoint(name = "SatisfactionOperateSoap12")
    public SatisfactionOperateSoap getSatisfactionOperateSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "SatisfactionOperateSoap12"), SatisfactionOperateSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SATISFACTIONOPERATE_EXCEPTION!= null) {
            throw SATISFACTIONOPERATE_EXCEPTION;
        }
        return SATISFACTIONOPERATE_WSDL_LOCATION;
    }

}
